ENCODER_MAP_ENABLE = yes
SEND_STRING_ENABLE = yes
OLED_DRIVER_ENABLE = yes
WPM_ENABLE = yes


# Disable features to reduce firmware size
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
BACKLIGHT_ENABLE = no
